apiVersion: v1
kind: ConfigMap
metadata:
  name: 'octane-env-configmap'
data:
  DB_SERVER_NAME: 'octane-mssql'
  DB_SERVER_PORT: '1433'
  SCHEMA_NAME: 'MF'
  DB_PROTOCOL: 'jdbc:sqlserver'
  DB_TYPE: 'MSSQL'
  DB_LOGIN_USER: 'octane'
  SCHEMA_PASSWORD: 'Password1'
  SITE_ACTION: 'CREATE_NEW'
  DISABLE_VALIDATOR_MEMORY: 'false'
  NGA_HEAP_SIZE: '4096'
  ELASTIC_HOST: 'octane-es'
  ELASTIC_PORT: '9300'
  ELASTIC_HTTP_PORT: '9200'
  ELASTIC_CLUSTER_NAME: 'octane'
  SITEADMINISTRATOR_USER: 'sa@nga'
  SITEADMINISTRATOR_PASSWORD: 'Password1'
  REPOSITORY_FOLDER: '/opt/octane/repo'
  CHANGE_LOG_FOLDER: 'true'
  APP_URL: 'http://nimbusserver.aos.com:8080'
  IS_CLUSTER: 'false'
  DEFAULT_SPACE_MODE: 'shared'
  DISABLE_DOS_FILTER: 'true'
  USE_CUSTOM_SECRET_FILE: 'true'
  DB_ADMIN_USER: 'sa'
  DB_ADMIN_PASSWORD: 'Password1'