apiVersion: v1
kind: ConfigMap
metadata:
  name: 'octane-env-configmap'
  namespace: '{{.Release.Namespace}}'
data:
  DB_SERVER_NAME: '{{.Values.db.server.name}}'
  DB_SERVER_PORT: '{{.Values.db.server.port}}'
  SCHEMA_NAME: '{{.Values.db.schema.name}}'
  SERVICE_NAME: '{{.Values.db.service}}'
  TABLE_SPACE: '{{.Values.db.tableSpace}}'
  TEMP_TABLE_SPACE: '{{.Values.db.tempTableSpace}}'
  DB_PROTOCOL: '{{.Values.db.protocol}}'
  DB_TYPE: '{{.Values.db.type}}'
  SITE_ACTION: '{{.Values.dbAction}}'
  DISABLE_VALIDATOR_MEMORY: '{{.Values.disableValidatorMemory}}'
  NGA_HEAP_SIZE: '{{.Values.ngaHeapSize}}'
  ELASTIC_HOST: '{{.Values.elasticsearch.host}}'
  ELASTIC_PORT: '{{.Values.elasticsearch.port}}'
  ELASTIC_CLUSTER_NAME: '{{.Values.elasticsearch.clusterName}}'
  SERVER_DOMAIN: '{{.Values.serverDomain}}'
  SITEADMINISTRATOR_USER: '{{.Values.siteAdminstratorUser}}'
  SITEADMINISTRATOR_PASSWORD: '{{.Values.siteAdminstratorPassword}}'
  REPOSITORY_FOLDER: '{{.Values.repositoryFolder}}'
  DISTRIBUTED_UUID: '{{.Values.distributedUuid}}'
  INSTALLATION_FOLDER: '{{.Values.installationFolder}}'
  WAR_FOLDER: '{{.Values.warFolder}}'
  ENABLE_SERVICES_INTEGRATION: '{{.Values.enableServiceIntegration}}'
  IS_SAAS: '{{.Values.isSaas}}'
  BACK_OFFICE: '{{.Values.backOffice}}'
  DOMAIN: '{{.Values.serverDomain}}'
  SSO_MASTER_LOGIN_URL: '{{.Values.ssoMasterLoginUrl}}'
  SSO_MASTER_LOGOUT_URL: '{{.Values.ssoMasterLogoutUrl}}'
  SSO_REDIRECT_TO_APP_URL: '{{.Values.ssoRedirectToAppUrl}}'
  SAAS_INTEGRATION_USERNAME: '{{.Values.saasIntegrationUsername}}'
  SAAS_INTEGRATION_PASSWORD: '{{.Values.saasIntegrationPassword}}'
  TERMINATE_SESSION_URL: '{{.Values.terminatedSessionsUrl}}'
  TERMINATE_SESSION_URL_TIMEOUT_SECONDS: '{{.Values.terminatedSessionsTimeoutSeconds}}'
  OAUTH_CLIENT_ID: '{{.Values.oauthClientId}}'
  OAUTH_CLIENT_SECRET: '{{.Values.oauthClientSecret}}'
  GET_OUATH_TOKEN_URL: '{{.Values.getOauthTokenUrl}}'
  PROXY_NAME: '{{.Values.proxy.host}}'
  PROXY_PORT: '{{.Values.proxy.port}}'
  NON_PROXY_HOSTS: '{{.Values.proxy.nonProxyHosts}}'
  EXPERIMENTS_ENV_TYPE: '{{.Values.experimentsEnvType}}'
  OCTANE_SITE_PARAM_PROMETHEUS_MONITOR_CAPQ: '{{.Values.siteParam.prometheusMonitor.CAPQ}}'
  OCTANE_SITE_PARAM_PROMETHEUS_MONITOR_DISTRUBUTED_CACHE: '{{.Values.siteParam.prometheusMonitor.distrubutedCache}}'
  OCTANE_SITE_PARAM_PROMETHEUS_MONITOR_JVM: '{{.Values.siteParam.prometheusMonitor.jvm}}'
  OCTANE_SITE_PARAM_PROMETHEUS_MONITOR_NON_DISTRIBUTED_CACHE: '{{.Values.siteParam.prometheusMonitor.nonDistrubutedCache}}'
  OCTANE_SITE_PARAM_PROMETHEUS_MONITOR_REST_API: '{{.Values.siteParam.prometheusMonitor.restApi}}'
  OCTANE_SITE_PARAM_EXPOSE_SERVER_TIMING_HEADER: '{{.Values.siteParam.exposeServerTimingHeader}}'
  OCTANE_SITE_PARAM_EXPOSE_FULL_EXCEPTION_FOR_REST: '{{.Values.siteParam.exposeFullExceptionForRest}}'
  OCTANE_SITE_PARAM_SUPPORT_EXTENSION_BUNDLES: '{{.Values.siteParam.supportExtensionBundles}}'
  KUBERNETES_NAMESPACE: '{{.Release.Namespace}}'
  CHANGE_LOG_FOLDER: 'true'
  APP_URL: '{{.Values.appUrl}}'
  SL_BDI_URL: '{{.Values.slBdiUrl}}'
  CONFIG_S3_APPENDER: '{{.Values.configS3Appender}}'
  CONFIG_JSON_APPENDER: '{{.Values.configJSONAppender}}'
  LOGGLY_OCTANE_INSTANCE: '{{.Release.Name}}'
  S3_LOG_BUCKET: '{{.Values.s3LogBucket}}'
  S3_LOG_PATH: '{{.Values.s3LogPath}}'
  S3_LOG_REGION: '{{.Values.s3LogRegion}}'
  SL_OPB_URL: '{{.Values.slOpbUrl}}'
  SL_SYNC_URL: '{{.Values.slSyncUrl}}'
  AUTHENTICATION_TYPE: '{{.Values.authenticationType}}'
  INTERNAL_SSO: '{{.Values.internalSso}}'
  SSO_LOGIN_SAML2_IDP_METADATA_URL: '{{.Values.idpUrl}}'
  ELASTIC_SNIFF: '{{.Values.elasticsearch.sniff}}'
  IS_CLUSTER: '{{.Values.cluster.isCluster}}'
  HAZELCAST_CLUSTER_NODES: '{{.Values.cluster.nodes}}'
  DEBUG: '{{.Values.enableDebug}}'
  DEBUG_PORT: '{{.Values.debugPort}}'
  NEW_UID: '{{.Values.global.docker_uid}}'
  NEW_GID: '{{.Values.global.docker_gid}}'
  ENABLE_SYNCX_INTEGRATION: 'true'
  DEFAULT_SPACE_MODE: 'shared'
  SET_XPACK: '{{.Values.setXPack}}'
  ELASTIC_KEYSTORE_PASS: '{{.Values.xpackKeystorePass}}'
  LOGS_UPLOAD_METHOD: '{{.Values.logs_upload_method}}'
  DEFAULT_SPACE_NAME: '{{.Values.defaultSharedSpaceName}}'
  DISABLE_DOS_FILTER: 'true'
  KUBERNETES_SERVICE_LABEL_VALUE: '{{.Values.hazelcastSlot}}'
  USER_JAVA_PROPERTIES: '{{.Values.javaProperties}}'
  LANGUAGES: '{{.Values.languages}}'
  USE_CUSTOM_SECRET_FILE: 'true'
  SCHEMA_PASSWORD='{{.Values.db.schema.password}}'
  DB_ADMIN_USER='{{.Values.db.admin.user}}'
  DB_ADMIN_PASSWORD='{{.Values.db.admin.password}}'
  DB_LOGIN_USER='{{.Values.db.server.dbLoginUser}}'
  ELASTICSEARCH_USERNAME='{{.Values.elasticsearch.username}}'
  ELASTICSEARCH_PASSWORD='{{.Values.elasticsearch.password}}'
  INIT_STRING='{{.Values.initString}}'
  AUTH_TOKEN_ENCRYPTION_KEY='{{.Values.authTokenEncryptionKey}}'
  INTERNAL_CERTIFICATE='{{.Values.internalCertificate}}'